name: Build and upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Dotnet Publish
      run: dotnet publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BitBox
        path: '/home/runner/work/BitBox/BitBox/bin/Release/net8.0/BitBox.dll'
    - name: Publish
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ github.workspace }}-BitBox.zip
        repository: auxy6858/BitBox
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}